// Destination selection is shared by the canvas map, keyboard panel and touch map.
'use strict';
const NAV=(()=>{
  let waypoint=null,root=null,cache={key:'',points:[]};
  try{const p=JSON.parse(localStorage.getItem('grift-city-waypoint'));if(p&&Number.isFinite(p.x)&&Number.isFinite(p.z))waypoint=p;}catch(e){}
  function set(p){waypoint=p?{x:p.x,z:p.z,y:p.y||0,label:p.label||'Waypoint',col:'#76e0d0'}:null;cache.key='';try{localStorage.setItem('grift-city-waypoint',JSON.stringify(waypoint));}catch(e){}refresh();}
  function destinations(){const out=[];for(const [kind,label] of [['safehouse','Safehouse'],['garage','Voss Motors'],['spray',"Pay ’n’ Spray"],['guns','Ironmonger'],['hospital','Hospital'],['docks','Pier 9'],['landmark','Landmark']])for(const p of CITY.places[kind]||[]){if(kind==='landmark'&&p.label==='tower')continue;out.push({...p,label:p.label&&p.label!=='tower'?p.label:label,y:p.label==='Switchback Deck'?3.8:0,kind});}const counts={};for(const p of out)counts[p.label]=(counts[p.label]||0)+1;for(const p of out)if(counts[p.label]>1)p.label+=' · '+CITY.districtName(p.x,p.z);return out;}
  function route(p,to){if(!to||p.car?.spec.boat||typeof STREETS==='undefined')return [];const key=[Math.round(p.x/12),Math.round(p.z/12),Math.round(p.y),to.x,to.z,to.y||0,p.car?.spec.wid||0].join(',');if(cache.key!==key){const nodes=STREETS.navigation(p,{...to,y:to.y||0},p.car?.spec.wid||0);cache={key,points:nodes.map(n=>[n.x,n.z])};}return cache.points;}
  function refresh(){if(!root)return;const p=PLAYER.P;root.querySelector('output').textContent=waypoint?waypoint.label+' · '+Math.round(M.dist(p.x,p.z,waypoint.x,waypoint.z))+' m':'Choose a destination or select a point on the map.';root.querySelector('[data-clear]').disabled=!waypoint;}
  function sync(state){if(state!=='map'){if(root)root.hidden=true;return;}if(!root){root=document.createElement('aside');root.id='map-nav';root.hidden=true;root.setAttribute('aria-label','City destinations');root.innerHTML='<small>GRIFT CITY / STREET GUIDE</small><h2>Where to?</h2><output aria-live="polite"></output><label>Destination<select aria-label="Destination"></select></label><div><button data-go>Set waypoint</button><button data-clear>Clear waypoint</button></div><p>Click or tap the map to mark a place. Roads and passages respect your vehicle’s width.</p><button data-close>Back to the street</button>';document.body.appendChild(root);const select=root.querySelector('select');for(const [i,p] of destinations().entries()){const o=document.createElement('option');o.value=i;o.textContent=p.label;select.appendChild(o);}root.querySelector('[data-go]').onclick=()=>set(destinations()[Number(select.value)]);root.querySelector('[data-clear]').onclick=()=>set(null);root.querySelector('[data-close]').onclick=()=>{GAME.state='playing';INPUT.releaseAll();};root.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();GAME.state='playing';INPUT.releaseAll();}});for(const e of ['pointerdown','mousedown','mouseup','touchstart','touchend','wheel'])root.addEventListener(e,e=>e.stopPropagation());}
    const opened=root.hidden;root.hidden=false;refresh();if(opened)root.querySelector('select').focus();
  }
  function mapClick(x,y,button=0){const r=HUD.mapRect;if(!r)return false;if(button===2){set(null);return true;}x/=r.uiScale;y/=r.uiScale;if(x<r.x||y<r.y||x>r.x+r.size||y>r.y+r.size)return false;const wx=(x-r.x)/r.scale+r.b0,wz=(y-r.y)/r.scale+r.b0;let point={x:wx,z:wz,y:0};for(const p of destinations())if(M.dist(wx,wz,p.x,p.z)*r.scale<14){point=p;break;}set(point);return true;}
  return {set,route,sync,mapClick,destinations,get waypoint(){return waypoint;}};
})();
