// GRIFT CITY — every texture is painted at runtime onto a 512² canvas. Alpha carries the emissive mask
// (lit windows, neon, signs) and is written straight into ImageData so the canvas never premultiplies it.
'use strict';
const TEX = (() => {
  const S = 512, NS = 320; // colour maps are painted at 512; normal and roughness at 320, which is plenty for them
  const layers = [], normals = [], panes = []; const names = {}; let shopKinds = [];
  const photos = {}; let curLayer = null; // decoded photographic materials (js/texdata.js), and the layer being painted
  // Decode every baked material. Called before build(); without it the painters fall back to their drawn colours.
  function preload(onProgress) {
    if (typeof TEXDATA === 'undefined') return Promise.resolve(0);
    const entries = Object.entries(TEXDATA.mats); let done = 0;
    const img = src => new Promise(res => { const im = new Image(); im.onload = () => res(im); im.onerror = () => res(null); im.src = src; });
    return Promise.all(entries.map(([name, e]) => Promise.all([img(e.c), e.n ? img(e.n) : null, e.r ? img(e.r) : null]).then(([c, n, r]) => {
      if (c) photos[name] = { c, n, r };
      if (onProgress) onProgress(++done / entries.length);
    }))).then(() => Object.keys(photos).length);
  }
  // The photographic base of the layer being painted: the material's colour map, blended toward the palette colour the
  // painter asks for (a restrained luminance blend keeps mortar and grain without overpowering the shapes). The normal
  // and roughness maps go to the parallel canvases at the same time. Returns false when the material is missing.
  function base(g, col, opts = {}) {
    const spec = typeof TEXDATA !== 'undefined' && curLayer && TEXDATA.layers[curLayer]; const im = spec && photos[spec[0]];
    if (!im) { if (col) { g.fillStyle = col; g.fillRect(0, 0, S, S); } return false; }
    g.drawImage(im.c, 0, 0, S, S);
    const amt = opts.amt !== undefined ? opts.amt : spec[1];
    if (col && amt > 0) {
      // Recolour toward the palette, compressing photographic contrast toward its luminance.
      // Surface grain survives, but no longer competes as strongly with silhouettes and signage.
      const t = parseHex(col); const tl = 0.299 * t[0] + 0.587 * t[1] + 0.114 * t[2] || 1;
      const kr = t[0] / tl, kg = t[1] / tl, kb = t[2] / tl, inv = 1 - amt;
      const id = g.getImageData(0, 0, S, S), d = id.data;
      for (let i = 0; i < d.length; i += 4) {
        const l = (0.299 * d[i] + 0.587 * d[i + 1] + 0.114 * d[i + 2]) * 0.65 + tl * 0.35;
        d[i] = inv * d[i] + amt * l * kr; d[i + 1] = inv * d[i + 1] + amt * l * kg; d[i + 2] = inv * d[i + 2] + amt * l * kb;
      }
      g.putImageData(id, 0, 0);
    }
    if (opts.dark) { g.save(); g.globalCompositeOperation = 'multiply'; g.globalAlpha = opts.dark; g.fillStyle = '#000'; g.fillRect(0, 0, S, S); g.restore(); }
    if (g._n && im.n) { g._n.drawImage(im.n, 0, 0, NS, NS); g._touched = true; }
    if (g._r && im.r) { g._r.drawImage(im.r, 0, 0, NS, NS); g._touched = true; }
    return true;
  }
  const parseHex = c => { if (c[0] !== '#') { const m = c.match(/[\d.]+/g); return m ? [+m[0], +m[1], +m[2]] : [128, 128, 128]; }
    const h = c.length === 4 ? c[1] + c[1] + c[2] + c[2] + c[3] + c[3] : c.slice(1); const v = parseInt(h, 16); return [(v >> 16) & 255, (v >> 8) & 255, v & 255]; };
  // Flatten a rectangle of the normal map and give it its own roughness: window glass, signs and painted panels are
  // smooth however bumpy the wall behind them is.
  function flatN(g, x, y, w, h, rough = 0.2) {
    if (!g._n) return; g._touched = true; const k = NS / S; const v = Math.round(M.clamp(rough, 0, 1) * 255);
    g._n.fillStyle = '#8080ff'; g._n.fillRect(x * k, y * k, w * k, h * k);
    g._r.fillStyle = `rgb(${v},${v},${v})`; g._r.fillRect(x * k, y * k, w * k, h * k);
  }
  // Normal in RGB, roughness in alpha, as one ImageData the renderer uploads.
  let flatMap = null;
  function packMaps(ng, rg, touched) {
    if (!touched) { // untouched layers all share one flat normal with a default roughness
      if (!flatMap) { const id = ng.getImageData(0, 0, NS, NS), d = id.data; for (let i = 0; i < d.length; i += 4) d[i + 3] = 180; flatMap = id; }
      return flatMap;
    }
    const n = ng.getImageData(0, 0, NS, NS), r = rg.getImageData(0, 0, NS, NS), dn = n.data, dr = r.data;
    for (let i = 0; i < dn.length; i += 4) dn[i + 3] = dr[i];
    return n;
  }
  function add(name, painter) {
    const c = document.createElement('canvas'); c.width = S; c.height = S;
    const g = c.getContext('2d'); g.fillStyle = '#000'; g.fillRect(0, 0, S, S); g._lit = [];
    const nc = document.createElement('canvas'); nc.width = nc.height = NS; const ng = nc.getContext('2d'); ng.fillStyle = '#8080ff'; ng.fillRect(0, 0, NS, NS);
    const rc = document.createElement('canvas'); rc.width = rc.height = NS; const rg = rc.getContext('2d'); rg.fillStyle = '#b4b4b4'; rg.fillRect(0, 0, NS, NS);
    g._n = ng; g._r = rg; g._touched = false; curLayer = name;
    painter(g, M.rng(layers.length * 7919 + 13));
    curLayer = null;
    names[name] = layers.length; layers.push(g._out || finish(g, g._lit)); normals.push(packMaps(ng, rg, g._touched)); panes.push(g._panes || null);
  }
  // Bake the emissive rectangles into alpha and hand back raw ImageData.
  function finish(g, rects, base = 0) {
    const id = g.getImageData(0, 0, S, S), d = id.data;
    for (let i = 3; i < d.length; i += 4) d[i] = base;
    for (const [x, y, w, h, a] of rects) { const v = a === undefined ? 255 : a; for (let yy = Math.max(0, Math.floor(y)); yy < Math.min(S, y + h); yy++) for (let xx = Math.max(0, Math.floor(x)); xx < Math.min(S, x + w); xx++) d[(yy * S + xx) * 4 + 3] = v; }
    return id;
  }
  const grain = (g, r, count = 20000, alpha = 0.07, size = 2) => { for (let i = 0; i < count; i++) { g.fillStyle = r() < 0.5 ? `rgba(0,0,0,${alpha})` : `rgba(255,255,255,${alpha})`; g.fillRect(r() * S, r() * S, size, size); } };
  const noise = (g, r, amount, count = 8000) => { for (let i = 0; i < count; i++) { const v = Math.floor(r() * amount); g.fillStyle = `rgba(${v},${v},${v},${0.2 + r() * 0.5})`; g.fillRect(r() * S, r() * S, 1 + r() * 4, 1 + r() * 4); } };
  const cracks = (g, r, n = 6, col = 'rgba(0,0,0,0.5)') => { g.strokeStyle = col; g.lineWidth = 1.5; for (let i = 0; i < n; i++) { let x = r() * S, y = r() * S; g.beginPath(); g.moveTo(x, y); for (let k = 0; k < 8 + r() * 10; k++) { x += (r() - 0.5) * 40; y += (r() - 0.5) * 40; g.lineTo(x, y); } g.stroke(); } };
  const stains = (g, r, n = 8, col = 'rgba(0,0,0,0.18)') => { for (let i = 0; i < n; i++) { g.fillStyle = col; g.beginPath(); g.ellipse(r() * S, r() * S, 10 + r() * 50, 6 + r() * 30, r() * 3, 0, 7); g.fill(); } };
  const streaks = (g, r, n, x0, x1, y0, len, col = 'rgba(0,0,0,0.12)') => { for (let i = 0; i < n; i++) { const x = x0 + r() * (x1 - x0); g.fillStyle = col; g.fillRect(x, y0, 1 + r() * 3, len * (0.3 + r() * 0.7)); } };
  // A window pane with frame, glass, mullions and (maybe) light behind it.
  function pane(g, r, x, y, w, h, o) {
    const lit = r() < o.litFrac;
    const fw = Math.max(1.5, Math.min(3, w * 0.07)); g.fillStyle = o.frame; g.fillRect(x - fw, y - fw, w + 2 * fw, h + 2 * fw);
    g.fillStyle = r() < 0.5 ? o.glassA : o.glassB; g.fillRect(x, y, w, h);
    // reflection gradient
    const gr = g.createLinearGradient(x, y, x + w * 0.35, y + h); gr.addColorStop(0, 'rgba(210,232,255,0.4)'); gr.addColorStop(0.45, 'rgba(160,190,225,0.12)'); gr.addColorStop(1, 'rgba(0,0,0,0.3)'); g.fillStyle = gr; g.fillRect(x, y, w, h);
    if (lit) { const cool = r() < 0.3; // a few floors are fluorescent rather than lamplit
      g.fillStyle = cool ? `rgba(${185 + r() * 40},${205 + r() * 40},${215 + r() * 40},${0.1 + r() * 0.1})` : `rgba(${200 + r() * 45},${170 + r() * 45},${110 + r() * 55},${0.12 + r() * 0.12})`;
      g.fillRect(x, y, w, h); if (r() < 0.5) { g.fillStyle = 'rgba(0,0,0,0.18)'; g.fillRect(x + w * r() * 0.5, y + h * 0.35, w * 0.28, h * 0.65); }
      g._lit.push([x, y, w, h, 105 + Math.floor(r() * r() * 150)]); }
    else if (r() < 0.4) { g.fillStyle = 'rgba(0,0,0,0.35)'; g.fillRect(x, y, w, h * (0.2 + r() * 0.55)); }
    if (o.mullion) { g.fillStyle = o.frame; g.fillRect(x + w / 2 - 1.5, y, 3, h); if (o.mullion > 1) g.fillRect(x, y + h * 0.4 - 1.5, w, 3); }
    if (o.sill) { g.fillStyle = o.sillCol || 'rgba(255,255,255,0.35)'; g.fillRect(x - 6, y + h + 3, w + 12, 5); g.fillStyle = 'rgba(0,0,0,0.35)'; g.fillRect(x - 6, y + h + 8, w + 12, 3); streaks(g, r, 3, x - 4, x + w + 4, y + h + 11, 30, 'rgba(0,0,0,0.1)'); }
    if (o.lintel) { g.fillStyle = 'rgba(255,255,255,0.25)'; g.fillRect(x - 6, y - 9, w + 12, 6); }
    if (o.arch) { g.fillStyle = o.frame; g.beginPath(); g.arc(x + w / 2, y + 2, w / 2 + 3, Math.PI, 0); g.fill(); g.fillStyle = r() < 0.5 ? o.glassA : o.glassB; g.beginPath(); g.arc(x + w / 2, y + 2, w / 2, Math.PI, 0); g.fill(); if (lit) { g.fillStyle = 'rgb(230,205,150)'; g.beginPath(); g.arc(x + w / 2, y + 2, w / 2, Math.PI, 0); g.fill(); g._lit.push([x, y - w / 2, w, w / 2 + 2, 170]); } }
    if (o.ac && r() < 0.25) { g.fillStyle = '#9a9a96'; g.fillRect(x + w * 0.55, y + h * 0.55, w * 0.42, h * 0.42); g.fillStyle = '#6a6a66'; for (let k = 0; k < 4; k++) g.fillRect(x + w * 0.58, y + h * 0.6 + k * h * 0.09, w * 0.36, 2); }
    flatN(g, x - 3, y - 3, w + 6, h + 6, 0.12); // glass and its frame: smooth and shiny
  }
  // A wall of windows: cols x rows panes with wall texture painted by `wall(g, r)` first.
  function windows(g, r, o) {
    o.wall(g, r); g._panes = [o.cols, o.rows, o.wPad, o.hPad];
    const cw = S / o.cols, ch = S / o.rows;
    for (let j = 0; j < o.rows; j++) {
      if (o.band) { g.fillStyle = o.band; g.fillRect(0, j * ch, S, 6); g.fillStyle = 'rgba(0,0,0,0.25)'; g.fillRect(0, j * ch + 6, S, 3); }
      for (let i = 0; i < o.cols; i++) { const x = i * cw + cw * o.wPad, y = j * ch + ch * o.hPad, w = cw * (1 - 2 * o.wPad), h = ch * (1 - 2 * o.hPad); pane(g, r, x, y, w, h, o);
        // the reveal: a window sits back in the wall, so its head and one jamb are in shadow and the sill below catches the light
        g.fillStyle = 'rgba(0,0,0,0.32)'; g.fillRect(x, y, w, Math.max(2, h * 0.11)); g.fillRect(x, y, Math.max(2, w * 0.07), h); g.fillStyle = 'rgba(255,255,255,0.16)'; g.fillRect(x - 2, y + h, w + 4, Math.max(2, h * 0.05)); g.fillStyle = 'rgba(0,0,0,0.22)'; g.fillRect(x - 2, y + h + Math.max(2, h * 0.05), w + 4, Math.max(2, h * 0.04)); }
    }
    if (o.pilasters) for (let i = 0; i <= o.cols; i++) { const x = i * cw - 8; g.fillStyle = 'rgba(255,255,255,0.14)'; g.fillRect(x, 0, 10, S); g.fillStyle = 'rgba(0,0,0,0.22)'; g.fillRect(x + 10, 0, 6, S); }
  }
  const bricks = (g, r, col, mortar, h = 10, w = 22) => { if (base(g, col)) { grain(g, r, 4000, 0.04); return; } g.fillStyle = col; g.fillRect(0, 0, S, S); for (let y = 0; y < S; y += h) { const off = (y / h) % 2 ? w / 2 : 0; for (let x = -w; x < S; x += w) { const v = r(); g.fillStyle = `rgba(${v < 0.5 ? 0 : 255},${v < 0.5 ? 0 : 255},${v < 0.5 ? 0 : 255},${0.04 + r() * 0.1})`; g.fillRect(x + off + 1, y + 1, w - 2, h - 2); } g.fillStyle = mortar; g.fillRect(0, y, S, 1.5); for (let x = -w; x < S; x += w) g.fillRect(x + off, y, 1.5, h); } grain(g, r, 8000, 0.05); };
  const stucco = (g, r, col) => { if (!base(g, col)) { g.fillStyle = col; g.fillRect(0, 0, S, S); grain(g, r, 30000, 0.05, 2); } stains(g, r, 5, 'rgba(0,0,0,0.08)'); };
  const concreteWall = (g, r, col) => { if (!base(g, col)) { g.fillStyle = col; g.fillRect(0, 0, S, S); grain(g, r, 24000, 0.05, 2); } for (let y = 0; y < S; y += 128) { g.fillStyle = 'rgba(0,0,0,0.25)'; g.fillRect(0, y, S, 2); } for (let x = 0; x < S; x += 128) { g.fillStyle = 'rgba(0,0,0,0.18)'; g.fillRect(x, 0, 2, S); } streaks(g, r, 40, 0, S, 0, 160, 'rgba(0,0,0,0.06)'); };

  function build() {
    const FONTS = { sans: '"Helvetica Neue", Arial, sans-serif', serif: 'Georgia, "Times New Roman", serif', slab: '"Courier New", monospace', script: '"Brush Script MT", "Comic Sans MS", cursive', heavy: 'Impact, "Arial Black", sans-serif' };
    add('white', g => { g.fillStyle = '#fff'; g.fillRect(0, 0, S, S); });
    add('asphalt', (g, r) => { if (!base(g, '#39393d')) { g.fillStyle = '#39393d'; g.fillRect(0, 0, S, S); noise(g, r, 70, 14000); grain(g, r, 20000, 0.05); } cracks(g, r, 5); stains(g, r, 6, 'rgba(0,0,0,0.15)'); for (let i = 0; i < 3; i++) { g.fillStyle = `rgba(${20 + r() * 20},${20 + r() * 20},${22 + r() * 20},0.5)`; g.fillRect(r() * S, r() * S, 40 + r() * 120, 30 + r() * 90); } });
    // Road: u across the full 14 units, v along (one tile = 16 units). Gutters, lanes, centre line, wear.
    add('road', (g, r) => {
      if (!base(g, '#37373b')) { g.fillStyle = '#37373b'; g.fillRect(0, 0, S, S); noise(g, r, 60, 12000); grain(g, r, 16000, 0.05); }
      for (const lc of [0.125, 0.375, 0.625, 0.875]) { g.fillStyle = 'rgba(0,0,0,0.13)'; g.fillRect((lc - 0.06) * S, 0, 0.12 * S, S); }
      cracks(g, r, 4, 'rgba(0,0,0,0.4)'); stains(g, r, 4, 'rgba(0,0,0,0.14)');
      for (let i = 0; i < 2; i++) { g.fillStyle = 'rgba(25,25,28,0.45)'; g.fillRect(r() * S, r() * S, 30 + r() * 60, 60 + r() * 120); }
      g.fillStyle = '#c9a227'; g.fillRect(S * 0.5 - 6, 0, 4, S); g.fillRect(S * 0.5 + 2, 0, 4, S); grain(g, r, 1500, 0.15, 2);
      g.fillStyle = '#d8d8d0'; for (let y = 0; y < S; y += 128) { g.fillRect(S * 0.25 - 2, y, 4, 56); g.fillRect(S * 0.75 - 2, y, 4, 56); }
      g.fillStyle = '#2a2a2d'; g.fillRect(0, 0, 10, S); g.fillRect(S - 10, 0, 10, S); g.fillStyle = 'rgba(255,255,255,0.08)'; g.fillRect(10, 0, 3, S); g.fillRect(S - 13, 0, 3, S);
    });
    add('sidewalk', (g, r) => {
      if (!base(g, '#8e8b85')) { g.fillStyle = '#8e8b85'; g.fillRect(0, 0, S, S); grain(g, r, 30000, 0.06, 2); }
      for (let j = 0; j < 4; j++) for (let i = 0; i < 4; i++) { g.fillStyle = `rgba(${r() < 0.5 ? 0 : 255},${r() < 0.5 ? 0 : 255},${r() < 0.5 ? 0 : 255},${r() * 0.06})`; g.fillRect(i * 128, j * 128, 128, 128); }
      g.strokeStyle = 'rgba(30,30,30,0.5)'; g.lineWidth = 3; for (let i = 0; i <= 4; i++) { g.beginPath(); g.moveTo(i * 128, 0); g.lineTo(i * 128, S); g.stroke(); g.beginPath(); g.moveTo(0, i * 128); g.lineTo(S, i * 128); g.stroke(); }
      cracks(g, r, 4, 'rgba(0,0,0,0.35)'); stains(g, r, 10, 'rgba(0,0,0,0.1)');
      for (let i = 0; i < 40; i++) { g.fillStyle = 'rgba(20,20,20,0.35)'; g.beginPath(); g.arc(r() * S, r() * S, 2 + r() * 3, 0, 7); g.fill(); } // gum
    });
    const glassA = '#3e566b', glassB = '#2d4256', dark = '#2a2f36';
    add('office', (g, r) => { windows(g, r, { cols: 7, rows: 4, wPad: 0.09, hPad: 0.2, wall: (g, r) => concreteWall(g, r, '#68727c'), frame: dark, glassA, glassB, litFrac: 0.55, mullion: 1, band: '#4a525a' }); });
    add('glass', (g, r) => { windows(g, r, { cols: 8, rows: 4, wPad: 0.05, hPad: 0.06, wall: (g, r) => { g.fillStyle = '#1c2a38'; g.fillRect(0, 0, S, S); }, frame: '#16202a', glassA: '#26465e', glassB: '#1d3a50', litFrac: 0.6, mullion: 2 }); const gr = g.createLinearGradient(0, 0, 0, S); gr.addColorStop(0, 'rgba(255,255,255,0.12)'); gr.addColorStop(1, 'rgba(0,0,0,0.1)'); g.fillStyle = gr; g.fillRect(0, 0, S, S); });
    add('brick', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.26, hPad: 0.22, wall: (g, r) => bricks(g, r, '#8a4a3a', 'rgba(230,220,200,0.55)'), frame: '#e8e0d0', glassA: '#4d5d6b', glassB: '#3b4a57', litFrac: 0.4, sill: true, sillCol: '#d8d0c0', arch: true }); streaks(g, r, 30, 0, S, 0, 120, 'rgba(0,0,0,0.08)'); });
    add('concrete', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.2, hPad: 0.27, wall: (g, r) => concreteWall(g, r, '#b1aba0'), frame: '#3a3a3a', glassA: '#41505c', glassB: '#2f3c47', litFrac: 0.35, sill: true, ac: true }); });
    add('tenement', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.28, hPad: 0.22, wall: (g, r) => { bricks(g, r, '#6d675b', 'rgba(200,190,170,0.4)', 9, 20); stains(g, r, 8, 'rgba(0,0,0,0.12)'); }, frame: '#2c2620', glassA: '#3d4a52', glassB: '#2c3840', litFrac: 0.45, sill: true, sillCol: '#a89c88', ac: true }); streaks(g, r, 40, 0, S, 0, 200, 'rgba(0,0,0,0.1)'); });
    add('deco', (g, r) => { windows(g, r, { cols: 6, rows: 4, wPad: 0.28, hPad: 0.14, wall: (g, r) => stucco(g, r, '#c9b89a'), frame: '#4a3d2e', glassA: '#3c4c5a', glassB: '#2e3d4a', litFrac: 0.5, pilasters: true, lintel: true }); });
    add('stone', (g, r) => { windows(g, r, { cols: 4, rows: 3, wPad: 0.27, hPad: 0.2, wall: (g, r) => { bricks(g, r, '#9c948a', 'rgba(60,55,50,0.5)', 42, 128); }, frame: '#e2dccf', glassA: '#4a5866', glassB: '#3a4754', litFrac: 0.3, arch: true, sill: true, sillCol: '#e2dccf' }); });
    add('brick2', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.27, hPad: 0.23, wall: (g, r) => bricks(g, r, '#6e4a3e', 'rgba(220,205,190,0.45)', 10, 22), frame: '#2a2622', glassA: '#4d5d6b', glassB: '#3b4a57', litFrac: 0.4, sill: true, sillCol: '#c8b8a0', lintel: true }); streaks(g, r, 30, 0, S, 0, 100, 'rgba(0,0,0,0.08)'); }); // brown brick, square heads
    add('brick3', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.26, hPad: 0.22, wall: (g, r) => { bricks(g, r, '#d8d2c6', 'rgba(120,110,100,0.35)', 10, 22); stains(g, r, 6, 'rgba(0,0,0,0.06)'); }, frame: '#2e3a30', glassA: '#3d4a52', glassB: '#2c3840', litFrac: 0.45, sill: true, sillCol: '#a8a098' }); }); // whitewashed brick, dark frames
    add('office2', (g, r) => { windows(g, r, { cols: 7, rows: 4, wPad: 0.08, hPad: 0.22, wall: (g, r) => concreteWall(g, r, '#3e4448'), frame: '#20242a', glassA: '#6a8aa0', glassB: '#5a7a90', litFrac: 0.6, mullion: 2, band: '#2a2e33' }); }); // dark stone bands, wide glass
    add('glass2', (g, r) => { windows(g, r, { cols: 8, rows: 4, wPad: 0.05, hPad: 0.06, wall: (g, r) => { g.fillStyle = '#e8ecee'; g.fillRect(0, 0, S, S); }, frame: '#d8dde0', glassA: '#31584f', glassB: '#274a45', litFrac: 0.55, mullion: 2 }); const gr = g.createLinearGradient(0, 0, 0, S); gr.addColorStop(0, 'rgba(255,255,255,0.15)'); gr.addColorStop(1, 'rgba(0,0,0,0.08)'); g.fillStyle = gr; g.fillRect(0, 0, S, S); }); // green glass in white mullions
    add('glass3', (g, r) => { windows(g, r, { cols: 6, rows: 4, wPad: 0.04, hPad: 0.05, wall: (g, r) => { g.fillStyle = '#2a2018'; g.fillRect(0, 0, S, S); }, frame: '#3a2c20', glassA: '#5d442a', glassB: '#4b3623', litFrac: 0.5, mullion: 1 }); const gr = g.createLinearGradient(0, 0, S, S); gr.addColorStop(0, 'rgba(255,240,200,0.18)'); gr.addColorStop(1, 'rgba(0,0,0,0.15)'); g.fillStyle = gr; g.fillRect(0, 0, S, S); }); // bronze glass
    add('warehouse', (g, r) => { if (!base(g, '#8a8c88')) { g.fillStyle = '#8a8c88'; g.fillRect(0, 0, S, S); } for (let x = 0; x < S; x += 12) { g.fillStyle = `rgba(0,0,0,${0.12 + r() * 0.1})`; g.fillRect(x, 0, 4, S); g.fillStyle = 'rgba(255,255,255,0.08)'; g.fillRect(x + 6, 0, 2, S); } streaks(g, r, 40, 0, S, 0, 200, 'rgba(120,60,20,0.18)'); stains(g, r, 10, 'rgba(90,50,20,0.15)'); for (let i = 0; i < 4; i++) { pane(g, r, 20 + i * 124, 30, 84, 60, { frame: '#3a3a3a', glassA: '#5a6a70', glassB: '#4a5a60', litFrac: 0.25, mullion: 2 }); } g.fillStyle = 'rgba(0,0,0,0.3)'; g.fillRect(0, 250, S, 6); g.fillStyle = 'rgba(0,0,0,0.3)'; g.fillRect(0, 506, S, 6); }); // corrugated metal with a strip of high windows
    add('stucco2', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.3, hPad: 0.24, wall: (g, r) => stucco(g, r, ['#e8d8b0', '#d8b8a0', '#c8d8c0', '#e0c8d0', '#f0e0c8'][Math.floor(r() * 5)]), frame: '#f8f4ec', glassA: '#4e5d6b', glassB: '#3d4c5a', litFrac: 0.4, sill: true, sillCol: '#f8f4ec' }); const cw = S / 4, ch = S / 4; for (let j = 0; j < 4; j++) for (let i = 0; i < 4; i++) { const x = i * cw + cw * 0.3, y = j * ch + ch * 0.24, w = cw * 0.4, h = ch * 0.52; const sc = ['#3a6a4a', '#4a5a8a', '#7a3a3a', '#5a5a5a'][Math.floor(r() * 4)]; g.fillStyle = sc; g.fillRect(x - 22, y, 16, h); g.fillRect(x + w + 6, y, 16, h); g.fillStyle = 'rgba(0,0,0,0.3)'; for (let k = 4; k < h; k += 7) { g.fillRect(x - 21, y + k, 14, 2); g.fillRect(x + w + 7, y + k, 14, 2); } } }); // pastel plaster with shutters
    add('loft', (g, r) => { windows(g, r, { cols: 3, rows: 3, wPad: 0.12, hPad: 0.12, wall: (g, r) => bricks(g, r, '#7a5040', 'rgba(210,190,170,0.4)', 10, 22), frame: '#2a2a2e', glassA: '#5a6a74', glassB: '#4a5a64', litFrac: 0.5, mullion: 2, lintel: true }); const cw = S / 3, ch = S / 3; g.fillStyle = '#2a2a2e'; for (let j = 0; j < 3; j++) for (let i = 0; i < 3; i++) { const x = i * cw + cw * 0.12, y = j * ch + ch * 0.12, w = cw * 0.76, h = ch * 0.76; for (let k = 1; k < 4; k++) g.fillRect(x + w * k / 4 - 1, y, 2, h); for (let k = 1; k < 3; k++) g.fillRect(x, y + h * k / 3 - 1, w, 2); } }); // industrial: big gridded windows in old brick
    // ghost signs: faded painted advertising on a blank brick wall
    const GHOST = [['DRINK', 'GRIFT COLA'], ['OKAFOR & SONS', 'SHIPPING'], ['HOTEL', 'ROOMS $2'], ['MARROW', 'HARDWARE'], ['CIGARS', '5 CENTS']];
    add('ghost', (g, r) => { bricks(g, r, '#8a4a3a', 'rgba(230,220,200,0.5)'); streaks(g, r, 30, 0, S, 0, 200, 'rgba(0,0,0,0.1)'); const gs = GHOST[Math.floor(r() * GHOST.length)]; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillStyle = 'rgba(240,230,210,0.32)'; g.fillRect(40, 60, 432, 392); g.fillStyle = 'rgba(30,20,20,0.35)'; g.font = `bold 92px ${FONTS.heavy}`; let sz = 92; while (g.measureText(gs[0]).width > 400 && sz > 40) { sz -= 4; g.font = `bold ${sz}px ${FONTS.heavy}`; } g.fillText(gs[0], 256, 180); g.font = `bold 60px ${FONTS.serif}`; sz = 60; while (g.measureText(gs[1]).width > 400 && sz > 30) { sz -= 4; g.font = `bold ${sz}px ${FONTS.serif}`; } g.fillText(gs[1], 256, 330); g.fillStyle = 'rgba(200,40,40,0.25)'; g.fillRect(120, 400, 272, 20); grain(g, r, 20000, 0.06, 3); });
    add('banner', (g, r) => { for (let i = 0; i < 4; i++) { const hue = Math.floor(r() * 360); g.fillStyle = `hsl(${hue},42%,40%)`; g.fillRect(i * 128, 0, 128, S); g.fillStyle = `hsl(${hue},48%,75%)`; g.fillRect(i * 128 + 20, 60, 88, 88); g.fillStyle = 'rgba(255,255,255,0.85)'; g.font = `bold 34px ${FONTS.sans}`; g.textAlign = 'center'; g.textBaseline = 'middle'; g.save(); g.translate(i * 128 + 64, 330); g.rotate(-Math.PI / 2); g.fillText(['GRIFT CITY', 'MUSEUM', 'OPERA', 'MARKET DAYS'][i], 0, 0); g.restore(); } }); // four hanging banners for downtown flagpoles
    add('painted', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.27, hPad: 0.24, wall: (g, r) => stucco(g, r, ['#c98a6a', '#d8c07a', '#8fb5a0', '#b58fa8'][Math.floor(r() * 4)]), frame: '#f3efe6', glassA: '#4e5d6b', glassB: '#3d4c5a', litFrac: 0.45, sill: true, sillCol: '#f3efe6' }); // shutters
      const cw = S / 4, ch = S / 4; for (let j = 0; j < 4; j++) for (let i = 0; i < 4; i++) { if (r() > 0.6) continue; const x = i * cw + cw * 0.27, y = j * ch + ch * 0.24, w = cw * 0.46, h = ch * 0.52; g.fillStyle = '#3d5a4a'; g.fillRect(x - 16, y, 12, h); g.fillRect(x + w + 4, y, 12, h); g.fillStyle = 'rgba(0,0,0,0.3)'; for (let k = 4; k < h; k += 6) { g.fillRect(x - 15, y + k, 10, 2); g.fillRect(x + w + 5, y + k, 10, 2); } } });
    // Shopfronts: one tile = 8 units (two shops), 4 tall. Sixteen kinds of shop, each with its own sign, window
    // and door, painted two to a tile; a tenth tile is two shuttered fronts. city.js mixes tiles along a wall.
    const SHOPS = {
      bodega:   { names: ['BODEGA', 'CORNER MART', 'LUCKY 7 GROCERY', 'DELI & GROCERY', 'FRESH MARKET', 'SUNRISE DELI', 'M & J GROCERY', 'QUICK STOP'], sign: 'stripes', hue: 10, font: 'heavy', win: 'produce', door: 'glass' },
      laundro:  { names: ['LAUNDROMAT', 'WASH & FOLD', 'SUDS', 'SPIN CYCLE', 'COIN WASH', 'BUBBLES'], sign: 'box', hue: 200, font: 'sans', win: 'washers', door: 'glass' },
      diner:    { names: ['GRIFT DINER', "MARLA'S", 'ALL NITE DINER', 'THE GRILL', "ROSIE'S", 'BLUE PLATE', 'STARLITE DINER', 'PIER 9 GRILL'], sign: 'neon', hue: 350, font: 'script', win: 'diner', door: 'chrome' },
      pharmacy: { names: ['PHARMACY', 'DRUGS', 'MARROW PHARMACY', 'RX EXPRESS', 'CITY CHEMIST', 'NORTHGATE DRUGS'], sign: 'box', hue: 140, font: 'sans', win: 'pharmacy', door: 'glass' },
      bar:      { names: ['BAR NONE', 'THE HOLLOW', 'DIVE', 'LAST CALL', "O'ROURKE'S", 'THE ANCHOR', 'GULL & CRANE', 'SALOON', 'THE VAULT', 'LUCKY DOG'], sign: 'neon', hue: 30, font: 'serif', win: 'bar', door: 'wood' },
      pawn:     { names: ['PAWN & GOLD', 'CASH 4 GOLD', 'BAIL BONDS', 'WE BUY GOLD', 'CHECKS CASHED', 'LOANS', 'EZ PAWN', 'GOLD & GUNS'], sign: 'board', hue: 48, font: 'heavy', win: 'pawn', door: 'bars' },
      books:    { names: ['BOOKS', 'USED BOOKS', 'LARK BOOKSHOP', 'MAPS & PRINTS', 'COMICS', 'THE READING ROOM', 'RARE BOOKS', 'PAPERBACKS'], sign: 'board', hue: 120, font: 'serif', win: 'books', door: 'wood' },
      cafe:     { names: ['CAFE MARROW', 'ESPRESSO', 'THE DAILY GRIND', 'CAFE', 'BEAN THERE', 'CORNER CAFE', 'TEA & TOAST', 'MOKA', 'CAFE LARK'], sign: 'board', hue: 25, font: 'script', win: 'cafe', door: 'wood' },
      barber:   { names: ['BARBER', 'CUTS', 'FADE CITY', "GINO'S BARBER", 'SALON', 'HAIR TODAY', 'THE CHAIR', 'CLIPPERS'], sign: 'box', hue: 210, font: 'serif', win: 'barber', door: 'glass' },
      tattoo:   { names: ['TATTOO', 'INK', 'PIERCING & INK', 'BLACK HEART TATTOO', 'NEEDLE & THREAD', 'IRON INK', 'SKIN DEEP'], sign: 'neon', hue: 300, font: 'heavy', win: 'tattoo', door: 'dark' },
      liquor:   { names: ['24H LIQUOR', 'LIQUOR', 'BEER WINE SPIRITS', 'DISCOUNT LIQUOR', 'WINE CELLAR', 'BOTTLE SHOP', 'SPIRITS', 'LOTTO & LIQUOR'], sign: 'stripes', hue: 0, font: 'heavy', win: 'liquor', door: 'bars' },
      noodle:   { names: ['NOODLE HOUSE', 'PHO 9', 'GOLDEN WOK', 'KEBAB', 'DUMPLINGS', 'TACOS', 'PIZZA SLICE', 'CURRY HOUSE', 'SUSHI', 'FALAFEL KING', 'RAMEN'], sign: 'box', hue: 0, font: 'sans', win: 'noodle', door: 'glass' },
      electro:  { names: ['ELECTRONICS', 'PHONES UNLOCKED', 'TV & AUDIO', 'REPAIRS', 'CAMERA WORLD', 'GAMES', 'HI-FI', 'COMPUTERS'], sign: 'box', hue: 220, font: 'sans', win: 'electro', door: 'glass' },
      clothes:  { names: ['BOUTIQUE', 'MENSWEAR', 'VINTAGE', 'SNEAKERS', 'THREADS', 'DENIM CO', 'SHOES', 'TAILOR', 'HATS', 'OUTFITTERS'], sign: 'board', hue: 330, font: 'serif', win: 'clothes', door: 'glass' },
      florist:  { names: ['FLOWERS', 'FLORIST', 'BLOOM', 'PETALS', 'ROSE & THORN', 'GARDEN SHOP', 'ORCHID'], sign: 'board', hue: 100, font: 'script', win: 'florist', door: 'glass' },
      bakery:   { names: ['BAKERY', 'FRESH BREAD', 'PATISSERIE', 'DONUTS', 'BAGELS', 'CAKE BOX', 'PIES', 'SOURDOUGH'], sign: 'board', hue: 38, font: 'script', win: 'bakery', door: 'wood' },
    };
    const textFit = (g, t, maxW, size, font, style = 'bold') => { let sz = size; g.font = `${style} ${sz}px ${font}`; while (g.measureText(t).width > maxW && sz > 14) { sz -= 2; g.font = `${style} ${sz}px ${font}`; } };
    // paints one shop of `kind` into the 256-wide slot at x0
    const usedNames = new Set(); const SIGN_ALT = { board: 'box', box: 'board', neon: 'board', stripes: 'board' };
    function shop(g, r, x0, kind) {
      const sp = { ...SHOPS[kind] }; if (r() < 0.3) sp.sign = SIGN_ALT[sp.sign]; const fresh = sp.names.filter(n => !usedNames.has(n)); const name = (fresh.length ? fresh : sp.names)[Math.floor(r() * (fresh.length ? fresh : sp.names).length)]; usedNames.add(name); const hue = (sp.hue + (r() - 0.5) * 40 + 360) % 360; const font = FONTS[sp.font];
      const dark = `hsl(${hue},30%,14%)`, mid = `hsl(${hue},34%,34%)`, light = `hsl(${hue},60%,85%)`;
      g.textAlign = 'center'; g.textBaseline = 'middle';
      // ---- sign band (14..90)
      if (sp.sign === 'board') { g.fillStyle = mid; g.fillRect(x0 + 6, 14, 244, 76); g.fillStyle = `hsl(${hue},34%,26%)`; g.fillRect(x0 + 6, 84, 244, 8); g.strokeStyle = light; g.lineWidth = 3; g.strokeRect(x0 + 14, 22, 228, 60); g.fillStyle = light; textFit(g, name, 216, 40, font); g.fillText(name, x0 + 128, 52); }
      else if (sp.sign === 'box') { g.fillStyle = '#2a2a2e'; g.fillRect(x0 + 6, 14, 244, 76); g.fillStyle = '#f4f2ea'; g.fillRect(x0 + 14, 22, 228, 60); g._lit.push([x0 + 14, 22, 228, 60]); g.fillStyle = `hsl(${hue},52%,38%)`; textFit(g, name, 216, 42, font); g.fillText(name, x0 + 128, 52); }
      else if (sp.sign === 'neon') { g.fillStyle = '#15151a'; g.fillRect(x0 + 6, 14, 244, 76); const col = `hsl(${hue},78%,66%)`; g.shadowColor = col; g.shadowBlur = 18; g.fillStyle = col; textFit(g, name, 210, 44, font, 'italic bold'); g.fillText(name, x0 + 128, 52); g.shadowBlur = 0; g._lit.push([x0 + 30, 26, 196, 52]); g.strokeStyle = `hsl(${hue},58%,40%)`; g.lineWidth = 2; g.strokeRect(x0 + 12, 20, 232, 64); }
      else { /* stripes: an awning-style band with the name on it */ for (let k = 0; k < 12; k++) { g.fillStyle = k % 2 ? mid : '#f0ebe0'; g.fillRect(x0 + 6 + k * 20.3, 14, 20.3, 76); } g.fillStyle = 'rgba(0,0,0,0.55)'; g.fillRect(x0 + 20, 32, 216, 40); g.fillStyle = '#fff'; textFit(g, name, 200, 34, font); g.fillText(name, x0 + 128, 52); }
      // ---- awning (some kinds) and the frame around the window
      const awning = sp.sign !== 'stripes' && r() < 0.45; if (awning) { const ac = `hsl(${(hue + 180) % 360},50%,42%)`; g.fillStyle = ac; g.fillRect(x0 + 6, 96, 244, 34); g.fillStyle = 'rgba(255,255,255,0.18)'; for (let k = 0; k < 6; k++) g.fillRect(x0 + 6 + k * 40.6, 96, 20, 34); g.fillStyle = 'rgba(0,0,0,0.3)'; g.fillRect(x0 + 6, 128, 244, 6); }
      const frameCol = sp.door === 'wood' ? '#3a2a1e' : sp.door === 'chrome' ? '#b8bcc4' : '#1c2228'; g.fillStyle = frameCol; g.fillRect(x0 + 14, 140, 228, 350);
      const wx = x0 + 22, wy = 148, ww = 130, wh = 334; // the display window
      // ---- window contents
      const w = sp.win; const lit = (x, y, ww2, hh) => g._lit.push([x, y, ww2, hh]);
      g.fillStyle = '#53606c'; g.fillRect(wx, wy, ww, wh);
      if (w === 'produce') { g.fillStyle = '#2b3a2a'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh * 0.4); const cols = ['#d33', '#e8a020', '#5cb040', '#f0d040', '#8c3', '#c60']; for (let j = 0; j < 4; j++) { g.fillStyle = '#6a4a2a'; g.fillRect(wx + 4, wy + 150 + j * 46, ww - 8, 8); for (let i = 0; i < 5; i++) { g.fillStyle = cols[Math.floor(r() * cols.length)]; for (let q = 0; q < 6; q++) { g.beginPath(); g.arc(wx + 14 + i * 24 + r() * 10, wy + 138 + j * 46 + r() * 10, 5, 0, 7); g.fill(); } } } g.fillStyle = '#e8e0c0'; g.fillRect(wx + 10, wy + 20, 60, 30); g.fillStyle = '#c33'; g.font = `bold 18px ${FONTS.heavy}`; g.fillText('FRESH', wx + 40, wy + 35); g.fillStyle = 'rgba(255,255,255,0.12)'; g.fillRect(wx, wy, 30, wh); }
      else if (w === 'washers') { g.fillStyle = '#d7e3ec'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); for (let j = 0; j < 3; j++) for (let i = 0; i < 2; i++) { const mx = wx + 12 + i * 60, my = wy + 40 + j * 96; g.fillStyle = '#eef1f4'; g.fillRect(mx, my, 50, 80); g.fillStyle = '#4a5560'; g.beginPath(); g.arc(mx + 25, my + 46, 18, 0, 7); g.fill(); g.fillStyle = '#7fa8c8'; g.beginPath(); g.arc(mx + 25, my + 46, 12, 0, 7); g.fill(); g.fillStyle = '#c33'; g.fillRect(mx + 8, my + 8, 8, 8); } }
      else if (w === 'diner') { g.fillStyle = '#5a2a2a'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); g.fillStyle = '#c62a2a'; g.fillRect(wx + 8, wy + 170, ww - 16, 60); g.fillStyle = '#e0d8c8'; g.fillRect(wx + 8, wy + 230, ww - 16, 20); for (let i = 0; i < 3; i++) { g.fillStyle = '#b8bcc4'; g.fillRect(wx + 20 + i * 40, wy + 250, 6, 60); g.fillStyle = '#c62a2a'; g.beginPath(); g.arc(wx + 23 + i * 40, wy + 250, 10, 0, 7); g.fill(); } g.shadowColor = '#ff6a6a'; g.shadowBlur = 12; g.fillStyle = '#ff8080'; g.font = `bold 22px ${FONTS.sans}`; g.fillText('OPEN 24H', wx + ww / 2, wy + 60); g.shadowBlur = 0; }
      else if (w === 'pharmacy') { g.fillStyle = '#f2f4f6'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); for (let j = 0; j < 4; j++) { g.fillStyle = '#d0d4d8'; g.fillRect(wx + 6, wy + 130 + j * 50, ww - 12, 6); for (let i = 0; i < 9; i++) { g.fillStyle = ['#fff', '#8fd', '#fc8', '#9bf', '#f99'][Math.floor(r() * 5)]; g.fillRect(wx + 8 + i * 13, wy + 108 + j * 50, 10, 22); } } g.shadowColor = '#4f8'; g.shadowBlur = 14; g.fillStyle = '#20d060'; g.fillRect(wx + ww / 2 - 8, wy + 20, 16, 56); g.fillRect(wx + ww / 2 - 28, wy + 40, 56, 16); g.shadowBlur = 0; }
      else if (w === 'bar') { g.fillStyle = '#1a1412'; g.fillRect(wx, wy, ww, wh); g.fillStyle = 'rgba(255,200,120,0.08)'; g.fillRect(wx, wy, ww, wh); g.shadowColor = '#ffb020'; g.shadowBlur = 16; g.fillStyle = '#ffc040'; g.font = `bold 26px ${FONTS.serif}`; g.fillText('BEER', wx + ww / 2, wy + 70); g.shadowColor = '#40c0ff'; g.fillStyle = '#60d0ff'; g.font = `bold 20px ${FONTS.sans}`; g.fillText('COLD', wx + ww / 2, wy + 110); g.shadowBlur = 0; lit(wx + 20, wy + 50, 90, 80); g.fillStyle = '#3a2a1e'; g.fillRect(wx, wy + 200, ww, 8); for (let i = 0; i < 4; i++) { g.fillStyle = ['#8a4a1a', '#2a6a2a', '#b0a070', '#6a1a1a'][i]; g.fillRect(wx + 12 + i * 30, wy + 160, 12, 40); } g.fillStyle = '#e8e0d0'; g.fillRect(wx + 30, wy + 230, 70, 90); g.fillStyle = '#c33'; g.font = `bold 14px ${FONTS.sans}`; g.fillText('LIVE', wx + 65, wy + 250); g.fillText('MUSIC', wx + 65, wy + 268); g.fillText('FRI', wx + 65, wy + 286); }
      else if (w === 'pawn') { g.fillStyle = '#3a3428'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh * 0.5); for (let i = 0; i < 3; i++) { g.fillStyle = ['#c9a050', '#8a5a30', '#d0d0d0'][i]; g.fillRect(wx + 12 + i * 40, wy + 60, 24, 70); g.fillRect(wx + 16 + i * 40, wy + 130, 16, 60); } g.fillStyle = '#ffe070'; g.font = `bold 20px ${FONTS.heavy}`; g.fillText('WE BUY', wx + ww / 2, wy + 230); g.fillText('GOLD', wx + ww / 2, wy + 256); g.fillStyle = '#222'; for (let i = 0; i < 6; i++) g.fillRect(wx + 8 + i * 21, wy, 4, wh); g.fillRect(wx, wy + 100, ww, 4); g.fillRect(wx, wy + 220, ww, 4); }
      else if (w === 'books') { g.fillStyle = '#3a2a1a'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); for (let j = 0; j < 5; j++) { g.fillStyle = '#5a4030'; g.fillRect(wx + 4, wy + 60 + j * 56, ww - 8, 6); let bx = wx + 8; while (bx < wx + ww - 12) { const bw = 6 + r() * 8; g.fillStyle = `hsl(${Math.floor(r() * 360)},45%,${35 + r() * 30}%)`; g.fillRect(bx, wy + 20 + j * 56, bw, 40 - r() * 10); bx += bw + 1; } } }
      else if (w === 'cafe') { g.fillStyle = '#e8dcc8'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); g.fillStyle = '#222'; g.fillRect(wx + 10, wy + 20, ww - 20, 110); g.fillStyle = '#eee'; g.font = `bold 16px ${FONTS.script}`; ['espresso  2', 'latte  3.5', 'pie  4', 'soup  6'].forEach((t, k) => g.fillText(t, wx + ww / 2, wy + 40 + k * 24)); g.fillStyle = '#6a4a2a'; g.fillRect(wx + 8, wy + 200, ww - 16, 6); for (let i = 0; i < 4; i++) { g.fillStyle = ['#d9a066', '#c88040', '#f0d0a0', '#a06030'][i]; g.beginPath(); g.ellipse(wx + 22 + i * 30, wy + 190, 12, 8, 0, 0, 7); g.fill(); } g.fillStyle = '#4a3a2a'; g.fillRect(wx + 20, wy + 250, 40, 6); g.fillRect(wx + 38, wy + 256, 4, 60); g.fillRect(wx + 70, wy + 250, 40, 6); g.fillRect(wx + 88, wy + 256, 4, 60); }
      else if (w === 'barber') { g.fillStyle = '#e0e6ea'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); g.fillStyle = '#9aa4ac'; g.fillRect(wx + 6, wy + 30, ww - 12, 120); g.fillStyle = 'rgba(255,255,255,0.5)'; g.fillRect(wx + 10, wy + 34, ww - 20, 112); for (let i = 0; i < 2; i++) { g.fillStyle = '#222'; g.fillRect(wx + 20 + i * 60, wy + 200, 40, 50); g.fillRect(wx + 28 + i * 60, wy + 250, 24, 40); g.fillStyle = '#c33'; g.fillRect(wx + 22 + i * 60, wy + 190, 36, 12); } for (let k = 0; k < 10; k++) { g.fillStyle = k % 2 ? '#c33' : '#fff'; g.fillRect(wx + ww - 22, wy + 20 + k * 12, 14, 12); } g.fillStyle = '#33c'; g.fillRect(wx + ww - 22, wy + 68, 14, 12); }
      else if (w === 'tattoo') { g.fillStyle = '#0c0c10'; g.fillRect(wx, wy, ww, wh); const cols = ['#ff3b8d', '#37d4ff', '#ffe23b', '#7dff5a', '#ff8c2b']; for (let k = 0; k < 14; k++) { g.fillStyle = cols[k % 5]; const sx = wx + 10 + r() * (ww - 30), sy = wy + 30 + r() * (wh - 80); g.beginPath(); if (k % 3 === 0) { g.arc(sx, sy, 8 + r() * 8, 0, 7); } else if (k % 3 === 1) { g.moveTo(sx, sy); g.lineTo(sx + 16, sy + 22); g.lineTo(sx - 14, sy + 20); } else { g.rect(sx, sy, 14, 20); } g.fill(); } g.shadowColor = '#ff3b8d'; g.shadowBlur = 16; g.fillStyle = '#ff6ab0'; g.font = `bold 24px ${FONTS.heavy}`; g.fillText('TATTOO', wx + ww / 2, wy + wh - 40); g.shadowBlur = 0; lit(wx + 10, wy + wh - 60, ww - 20, 40); }
      else if (w === 'liquor') { g.fillStyle = '#1e1a16'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh * 0.6); for (let j = 0; j < 5; j++) { g.fillStyle = '#4a3a2a'; g.fillRect(wx + 4, wy + 70 + j * 52, ww - 8, 5); for (let i = 0; i < 10; i++) { g.fillStyle = ['#c8a040', '#2a6a2a', '#6a1a1a', '#e0e0e0', '#3a8ac0'][Math.floor(r() * 5)]; g.fillRect(wx + 8 + i * 12, wy + 40 + j * 52, 7, 30); g.fillRect(wx + 10 + i * 12, wy + 32 + j * 52, 3, 8); } } g.shadowColor = '#ff4040'; g.shadowBlur = 14; g.fillStyle = '#ff6060'; g.font = `bold 22px ${FONTS.heavy}`; g.fillText('24 HRS', wx + ww / 2, wy + 20); g.shadowBlur = 0; g.fillStyle = '#222'; for (let i = 0; i < 5; i++) g.fillRect(wx + 12 + i * 26, wy, 4, wh); }
      else if (w === 'noodle') { g.fillStyle = '#7a1a1a'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); for (let i = 0; i < 3; i++) { g.fillStyle = '#ff3020'; g.beginPath(); g.ellipse(wx + 25 + i * 40, wy + 40, 14, 18, 0, 0, 7); g.fill(); g.fillStyle = '#ffd040'; g.fillRect(wx + 22 + i * 40, wy + 56, 6, 12); g.fillRect(wx + 18 + i * 40, wy + 20, 14, 3); } g.fillStyle = '#f8e8c0'; g.fillRect(wx + 12, wy + 100, ww - 24, 150); g.fillStyle = '#7a1a1a'; g.font = `bold 15px ${FONTS.sans}`; ['NOODLE SOUP  8', 'DUMPLINGS  6', 'RICE BOWL  7', 'TEA  2'].forEach((t, k) => g.fillText(t, wx + ww / 2, wy + 120 + k * 30)); g.fillStyle = '#ffd040'; g.font = `bold 20px ${FONTS.heavy}`; g.fillText('OPEN', wx + ww / 2, wy + 290); }
      else if (w === 'electro') { g.fillStyle = '#20242a'; g.fillRect(wx, wy, ww, wh); for (let j = 0; j < 3; j++) for (let i = 0; i < 2; i++) { const tx = wx + 10 + i * 60, ty = wy + 30 + j * 100; g.fillStyle = '#0a0a0a'; g.fillRect(tx, ty, 50, 36); g.fillStyle = `hsl(${Math.floor(r() * 360)},70%,55%)`; g.fillRect(tx + 3, ty + 3, 44, 30); lit(tx + 3, ty + 3, 44, 30); g.fillStyle = '#ddd'; g.fillRect(tx + 8, ty + 44, 34, 18); g.fillStyle = '#4a9cff'; g.font = `bold 11px ${FONTS.sans}`; g.fillText('$' + (99 + Math.floor(r() * 9) * 100), tx + 25, ty + 53); } g.fillStyle = '#ffe23b'; g.font = `bold 18px ${FONTS.heavy}`; g.fillText('SALE', wx + ww / 2, wy + wh - 16); }
      else if (w === 'clothes') { g.fillStyle = '#f0ece4'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); for (let i = 0; i < 2; i++) { const mx = wx + 30 + i * 60; g.fillStyle = '#e8d8c8'; g.beginPath(); g.arc(mx, wy + 70, 12, 0, 7); g.fill(); g.fillStyle = `hsl(${Math.floor(r() * 360)},40%,45%)`; g.fillRect(mx - 18, wy + 86, 36, 70); g.fillStyle = `hsl(${Math.floor(r() * 360)},25%,30%)`; g.fillRect(mx - 16, wy + 156, 14, 90); g.fillRect(mx + 2, wy + 156, 14, 90); g.fillStyle = '#888'; g.fillRect(mx - 2, wy + 246, 4, 40); g.fillRect(mx - 14, wy + 286, 28, 4); } g.fillStyle = '#c33'; g.fillRect(wx + 8, wy + 10, 50, 22); g.fillStyle = '#fff'; g.font = `bold 14px ${FONTS.sans}`; g.fillText('-30%', wx + 33, wy + 21); }
      else if (w === 'florist') { g.fillStyle = '#5a7a4a'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh * 0.5); for (let j = 0; j < 3; j++) for (let i = 0; i < 4; i++) { const fx = wx + 18 + i * 30, fy = wy + 70 + j * 90; g.fillStyle = '#3a3a3a'; g.fillRect(fx - 10, fy, 20, 40); g.fillStyle = '#2f7a2a'; g.fillRect(fx - 12, fy - 20, 24, 24); const c = ['#ff5a7a', '#ffd23b', '#ffffff', '#c86bff', '#ff8c2b'][Math.floor(r() * 5)]; g.fillStyle = c; for (let q = 0; q < 7; q++) { g.beginPath(); g.arc(fx - 10 + r() * 20, fy - 26 + r() * 16, 4, 0, 7); g.fill(); } } }
      else if (w === 'bakery') { g.fillStyle = '#f4e4c8'; g.fillRect(wx, wy, ww, wh); lit(wx, wy, ww, wh); for (let j = 0; j < 4; j++) { g.fillStyle = '#8a6a4a'; g.fillRect(wx + 6, wy + 90 + j * 60, ww - 12, 6); for (let i = 0; i < 5; i++) { g.fillStyle = ['#d9a066', '#c88040', '#e8c090', '#a06030', '#f0d8b0'][Math.floor(r() * 5)]; g.beginPath(); g.ellipse(wx + 18 + i * 24, wy + 78 + j * 60, 10, 6 + r() * 4, 0, 0, 7); g.fill(); } } g.fillStyle = '#8a3a2a'; g.font = `bold 20px ${FONTS.script}`; g.fillText('fresh daily', wx + ww / 2, wy + 40); }
      // reflection and a little dirt on every window
      const gr = g.createLinearGradient(wx, wy, wx + ww, wy + wh); gr.addColorStop(0, 'rgba(255,255,255,0.16)'); gr.addColorStop(0.45, 'rgba(255,255,255,0.02)'); gr.addColorStop(1, 'rgba(0,0,0,0.1)'); g.fillStyle = gr; g.fillRect(wx, wy, ww, wh);
      if (r() < 0.5) { g.fillStyle = '#f4f2ea'; g.fillRect(wx + ww - 46, wy + wh - 40, 40, 28); g.fillStyle = '#c33'; g.font = `bold 13px ${FONTS.sans}`; g.fillText('OPEN', wx + ww - 26, wy + wh - 26); }
      // ---- door (x0+164..234)
      const dx = x0 + 164, dy = 148, dw = 70, dh = 334;
      if (sp.door === 'wood') { g.fillStyle = '#4a3020'; g.fillRect(dx, dy, dw, dh); g.fillStyle = '#5b4030'; g.fillRect(dx + 8, dy + 8, 54, 130); g.fillRect(dx + 8, dy + 150, 54, 170); g.fillStyle = '#c9b070'; g.fillRect(dx + 56, dy + 170, 6, 16); }
      else if (sp.door === 'chrome') { g.fillStyle = '#b8bcc4'; g.fillRect(dx, dy, dw, dh); g.fillStyle = '#556f84'; g.fillRect(dx + 8, dy + 8, 54, 250); lit(dx + 8, dy + 8, 54, 250); g.fillStyle = '#d8dce0'; g.fillRect(dx + 8, dy + 258, 54, 68); g.fillStyle = '#333'; g.fillRect(dx + 52, dy + 150, 4, 30); }
      else if (sp.door === 'bars') { g.fillStyle = '#222'; g.fillRect(dx, dy, dw, dh); g.fillStyle = '#3a3a40'; g.fillRect(dx + 6, dy + 6, 58, 320); for (let i = 0; i < 5; i++) { g.fillStyle = '#111'; g.fillRect(dx + 10 + i * 12, dy + 6, 3, 320); } g.fillStyle = '#c33'; g.fillRect(dx + 14, dy + 40, 42, 20); g.fillStyle = '#fff'; g.font = `bold 11px ${FONTS.sans}`; g.fillText('RING BELL', dx + 35, dy + 50); }
      else if (sp.door === 'dark') { g.fillStyle = '#0c0c10'; g.fillRect(dx, dy, dw, dh); g.fillStyle = '#1c1c22'; g.fillRect(dx + 8, dy + 8, 54, 240); g.fillStyle = '#ff3b8d'; g.fillRect(dx + 20, dy + 100, 30, 6); }
      else { g.fillStyle = '#2a3a48'; g.fillRect(dx, dy, dw, dh); g.fillStyle = '#556f84'; g.fillRect(dx + 8, dy + 8, 54, 260); lit(dx + 8, dy + 8, 54, 260); g.fillStyle = '#c9b070'; g.fillRect(dx + 52, dy + 160, 6, 18); g.fillStyle = 'rgba(255,255,255,0.15)'; g.fillRect(dx + 12, dy + 12, 14, 250); g.fillStyle = '#e8e0c8'; g.fillRect(dx + 16, dy + 30, 38, 22); g.fillStyle = '#333'; g.font = `bold 10px ${FONTS.sans}`; g.fillText('PUSH', dx + 35, dy + 41); }
      g.fillStyle = '#6a6560'; g.fillRect(x0 + 14, 486, 228, 12); // step
      if (r() < 0.35) { const py = 300 + r() * 120; g.fillStyle = ['#ffe23b', '#37d4ff', '#ff8c2b', '#fff'][Math.floor(r() * 4)]; g.fillRect(x0 + 238, py, 12, 40); } // a flyer on the door frame
    }
    const SHOP_TILES = [['bodega', 'laundro'], ['diner', 'pharmacy'], ['bar', 'pawn'], ['books', 'cafe'], ['barber', 'tattoo'], ['liquor', 'noodle'], ['electro', 'clothes'], ['florist', 'bakery'], ['cafe', 'clothes'],
      ['noodle', 'bar'], ['clothes', 'cafe'], ['bodega', 'pawn'], ['electro', 'diner'], ['barber', 'liquor'], ['bakery', 'books'], ['noodle', 'clothes'], ['cafe', 'florist'], ['pharmacy', 'bodega'], ['bar', 'electro'], ['laundro', 'noodle']];
    shopKinds = SHOP_TILES; SHOP_TILES.forEach((pair, v) => add('shops' + v, (g, r) => { g.fillStyle = '#4a4540'; g.fillRect(0, 0, S, S); grain(g, r, 8000, 0.05); shop(g, r, 0, pair[0]); shop(g, r, 256, pair[1]); }));
    // two shuttered fronts: roll-down doors, flyposting, a FOR LEASE sign
    add('shops20', (g, r) => { g.fillStyle = '#3e3a36'; g.fillRect(0, 0, S, S); grain(g, r, 8000, 0.06);
      for (let i = 0; i < 2; i++) { const x0 = i * 256; g.fillStyle = i ? '#5a5650' : '#6a5a48'; g.fillRect(x0 + 6, 14, 244, 76); g.fillStyle = 'rgba(0,0,0,0.35)'; g.fillRect(x0 + 6, 14, 244, 76); g.fillStyle = 'rgba(255,255,255,0.25)'; g.font = `bold 30px ${FONTS.sans}`; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText(i ? 'FOR LEASE' : '', x0 + 128, 52);
        g.fillStyle = '#4a4a4c'; g.fillRect(x0 + 14, 140, 228, 350); for (let y = 148; y < 486; y += 14) { g.fillStyle = 'rgba(0,0,0,0.35)'; g.fillRect(x0 + 14, y, 228, 4); g.fillStyle = 'rgba(255,255,255,0.08)'; g.fillRect(x0 + 14, y + 8, 228, 2); }
        for (let k = 0; k < 5; k++) { const px = x0 + 20 + r() * 180, py = 180 + r() * 220; g.fillStyle = ['#ffe23b', '#37d4ff', '#ff8c2b', '#f4f2ea', '#ff3b8d'][Math.floor(r() * 5)]; g.fillRect(px, py, 40, 56); g.fillStyle = 'rgba(0,0,0,0.6)'; g.fillRect(px + 6, py + 8, 28, 6); g.fillRect(px + 6, py + 20, 28, 20); }
        g.strokeStyle = ['#ff3b8d', '#37d4ff', '#7dff5a'][i]; g.lineWidth = 6; g.beginPath(); let gx = x0 + 30, gy = 300 + r() * 100; g.moveTo(gx, gy); for (let k = 0; k < 6; k++) { gx += 30; gy += (r() - 0.5) * 60; g.lineTo(gx, gy); } g.stroke();
        g.fillStyle = '#6a6560'; g.fillRect(x0 + 14, 486, 228, 12); } });
    add('roof', (g, r) => { if (!base(g, '#56534f')) { g.fillStyle = '#56534f'; g.fillRect(0, 0, S, S); noise(g, r, 80, 20000); grain(g, r, 20000, 0.05); } stains(g, r, 6, 'rgba(0,0,0,0.12)'); g.fillStyle = 'rgba(0,0,0,0.25)'; g.fillRect(0, 0, S, 14); g.fillRect(0, 0, 14, S); for (let i = 0; i < 3; i++) { g.fillStyle = 'rgba(255,255,255,0.08)'; g.fillRect(r() * S, r() * S, 60 + r() * 100, 40 + r() * 60); } });
    add('grass', (g, r) => { if (!base(g, '#566e46')) { g.fillStyle = '#566e46'; g.fillRect(0, 0, S, S); for (let i = 0; i < 30000; i++) { g.fillStyle = r() < 0.5 ? 'rgba(20,60,10,0.35)' : 'rgba(150,200,80,0.28)'; g.fillRect(r() * S, r() * S, 1, 2 + r() * 4); } } for (let i = 0; i < 12; i++) { g.fillStyle = 'rgba(90,70,40,0.25)'; g.beginPath(); g.ellipse(r() * S, r() * S, 10 + r() * 30, 6 + r() * 16, r() * 3, 0, 7); g.fill(); } });
    add('parking', (g, r) => { if (!base(g, '#48484a')) { g.fillStyle = '#48484a'; g.fillRect(0, 0, S, S); noise(g, r, 60, 12000); cracks(g, r, 5); } stains(g, r, 8, 'rgba(0,0,0,0.25)'); g.fillStyle = '#d0d0c8'; for (let x = 0; x < S; x += 128) { g.fillRect(x, 0, 5, S * 0.45); g.fillRect(x, S * 0.55, 5, S * 0.45); } });
    add('water', (g, r) => { g.fillStyle = '#1e4862'; g.fillRect(0, 0, S, S); for (let i = 0; i < 900; i++) { g.fillStyle = `rgba(170,215,240,${0.05 + r() * 0.16})`; g.fillRect(r() * S, r() * S, 16 + r() * 70, 1 + r() * 3); } for (let i = 0; i < 300; i++) { g.fillStyle = `rgba(10,30,50,${0.1 + r() * 0.2})`; g.fillRect(r() * S, r() * S, 20 + r() * 60, 2 + r() * 3); } });
    add('metal', (g, r) => { if (!base(g, '#7c8088')) { g.fillStyle = '#7c8088'; g.fillRect(0, 0, S, S); } for (let y = 0; y < S; y += 4) { g.fillStyle = `rgba(0,0,0,${0.06 + r() * 0.12})`; g.fillRect(0, y, S, 2); } streaks(g, r, 30, 0, S, 0, 300, 'rgba(120,70,30,0.12)'); grain(g, r, 6000, 0.05); });
    add('garage', (g, r) => { g.fillStyle = '#7d7a72'; g.fillRect(0, 0, S, S); grain(g, r, 12000, 0.06); g.fillStyle = '#4e5660'; g.fillRect(48, 80, 416, 432); for (let y = 96; y < S; y += 40) { g.fillStyle = 'rgba(0,0,0,0.3)'; g.fillRect(48, y, 416, 5); g.fillStyle = 'rgba(255,255,255,0.08)'; g.fillRect(48, y + 5, 416, 3); } g.fillStyle = '#e0c060'; g.fillRect(48, 24, 416, 40); streaks(g, r, 20, 48, 464, 80, 200, 'rgba(0,0,0,0.12)'); });
    const BILL = [['GRIFT COLA', 'taste the hustle', '#1b7fd6', '#ffffff'], ['VOSS MOTORS', 'drive like you mean it', '#c62a4a', '#ffe9a0'], ['CRANE HOLDINGS', 'the city, managed', '#1f2a3a', '#dfe6f0'], ['NEON FM 98.1', 'all night, every night', '#7a1fb5', '#ff9ff3'], ['IRONMONGER', 'sporting goods & more', '#3a3a3a', '#f1c40f'], ['ST. MARROW', 'we patch anyone', '#f4f4f4', '#c0281e']];
    BILL.forEach((bd, i) => add('bill' + i, (g, r) => { g.fillStyle = '#101418'; g.fillRect(0, 0, S, S); g.fillStyle = bd[2]; g.fillRect(16, 16, 480, 480); g.fillStyle = bd[3]; g.textAlign = 'center'; g.textBaseline = 'middle'; g.font = 'bold 70px "Helvetica Neue", Arial, sans-serif'; let sz = 70; while (g.measureText(bd[0]).width > 440 && sz > 30) { sz -= 4; g.font = `bold ${sz}px "Helvetica Neue", Arial, sans-serif`; } g.fillText(bd[0], 256, 200); g.font = 'italic 34px "Helvetica Neue", Arial, sans-serif'; g.fillText(bd[1], 256, 300); g.fillStyle = 'rgba(255,255,255,0.12)'; g.beginPath(); g.arc(400, 400, 60, 0, 7); g.fill(); g._lit.push([16, 16, 480, 480]); }));
    for (const [n, col] of [['neon', '#ff40a0'], ['neonc', '#40e0ff'], ['neony', '#ffd040'], ['neong', '#60ff80']]) add(n, g => { g.fillStyle = col; g.fillRect(0, 0, S, S); g._lit.push([0, 0, S, S]); });
    add('sand', (g, r) => { if (!base(g, '#cbb886')) { g.fillStyle = '#cbb886'; g.fillRect(0, 0, S, S); grain(g, r, 40000, 0.06); } for (let i = 0; i < 40; i++) { g.fillStyle = 'rgba(0,0,0,0.05)'; g.fillRect(0, r() * S, S, 2 + r() * 3); } });
    add('hospital', (g, r) => { windows(g, r, { cols: 4, rows: 4, wPad: 0.2, hPad: 0.22, wall: (g, r) => { concreteWall(g, r, '#e6e3dc'); }, frame: '#8a9aa6', glassA: '#2b3a44', glassB: '#354652', litFrac: 0.7, sill: true, sillCol: '#f5f5f2' }); });
    add('graffiti', (g, r) => { g.fillStyle = '#000'; g.fillRect(0, 0, S, S); const cols = ['#ff3b8d', '#37d4ff', '#ffe23b', '#7dff5a', '#ff8c2b', '#ffffff']; for (let i = 0; i < 5; i++) { g.strokeStyle = cols[Math.floor(r() * cols.length)]; g.lineWidth = 10 + r() * 14; g.lineCap = 'round'; g.beginPath(); let x = 60 + r() * 380, y = 100 + r() * 300; g.moveTo(x, y); for (let k = 0; k < 6; k++) { x += (r() - 0.5) * 200; y += (r() - 0.5) * 120; g.lineTo(x, y); } g.stroke(); } g.font = 'bold 90px Impact, "Arial Black", sans-serif'; g.fillStyle = cols[Math.floor(r() * cols.length)]; g.textAlign = 'center'; g.fillText(['GRIFT', 'CRANE OUT', 'PIER 9', 'NORTHGATE', 'VOSS', 'EAST SIDE'][Math.floor(r() * 6)], 256, 290); g._out = (() => { const id = g.getImageData(0, 0, S, S), d = id.data; for (let i = 0; i < d.length; i += 4) { const l = d[i] + d[i + 1] + d[i + 2]; d[i + 3] = l > 30 ? 255 : 0; } return id; })(); });
    // Street name signs: 16 rows, one name each; a quad maps to one row.
    const STREETS = ['MARROW AVE', 'CRANE ST', 'VOSS BLVD', 'PIER RD', 'LARK ST', 'HOLLOW WAY', 'GULL AVE', 'FERRY ST', 'IRON ST', 'OKAFOR DR', 'NORTHGATE', 'WESTFIELD', 'EASTSIDE AVE', 'SOUTHPORT', 'MIDTOWN', 'GRIFT PKWY'];
    add('signs', (g, r) => { STREETS.forEach((n, i) => { const y = i * 32; g.fillStyle = '#1f6b3a'; g.fillRect(0, y, S, 32); g.fillStyle = '#fff'; g.fillRect(0, y + 1, S, 1); g.fillRect(0, y + 30, S, 1); g.font = 'bold 22px "Helvetica Neue", Arial, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillText(n, 256, y + 16); }); });
    add('police', (g, r) => { g.fillStyle = '#f2f2f4'; g.fillRect(0, 0, S, S); g.fillStyle = '#111318'; g.fillRect(0, 0, S, 160); g.fillRect(0, 352, S, 160); g.fillStyle = '#1b3a8a'; g.fillRect(0, 160, S, 24); g.fillRect(0, 328, S, 24); g.font = 'bold 84px "Helvetica Neue", Arial, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillStyle = '#111318'; g.fillText('POLICE', 256, 256); g.fillStyle = '#c9a227'; g.beginPath(); g.arc(70, 256, 30, 0, 7); g.fill(); g.fillStyle = '#111318'; g.font = 'bold 22px sans-serif'; g.fillText('GCPD', 70, 256); });
    add('taxi', (g, r) => { g.fillStyle = '#f5c518'; g.fillRect(0, 0, S, S); for (let j = 0; j < 2; j++) for (let i = 0; i < 16; i++) { g.fillStyle = (i + j) % 2 ? '#111' : '#fff'; g.fillRect(i * 32, 224 + j * 32, 32, 32); } g.font = 'bold 60px "Helvetica Neue", Arial, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.fillStyle = '#111'; g.fillText('CABCO', 256, 130); });
    add('planks', (g, r) => { if (!base(g, '#7a5a3a')) { g.fillStyle = '#7a5a3a'; g.fillRect(0, 0, S, S); } for (let y = 0; y < S; y += 32) { g.fillStyle = `rgba(${r() < 0.5 ? 0 : 255},${r() < 0.5 ? 0 : 255},${r() < 0.5 ? 0 : 255},${r() * 0.1})`; g.fillRect(0, y, S, 32); g.fillStyle = 'rgba(0,0,0,0.5)'; g.fillRect(0, y, S, 2); } grain(g, r, 20000, 0.05); streaks(g, r, 30, 0, S, 0, 100, 'rgba(0,0,0,0.1)'); });
    add('flowers', (g, r) => { g.fillStyle = '#3c6a2c'; g.fillRect(0, 0, S, S); for (let i = 0; i < 400; i++) { g.fillStyle = ['#ff5a7a', '#ffd23b', '#ffffff', '#c86bff', '#ff8c2b'][Math.floor(r() * 5)]; g.beginPath(); g.arc(r() * S, r() * S, 4 + r() * 6, 0, 7); g.fill(); } });
    // test card for the visual test suite: red top-left, green top-right, blue bottom-left, orange bottom-right
    add('testcard', (g, r) => { g.fillStyle = '#ff0000'; g.fillRect(0, 0, S / 2, S / 2); g.fillStyle = '#00ff00'; g.fillRect(S / 2, 0, S / 2, S / 2); g.fillStyle = '#0000ff'; g.fillRect(0, S / 2, S / 2, S / 2); g.fillStyle = '#ff7f00'; g.fillRect(S / 2, S / 2, S / 2, S / 2); });
    add('manhole', (g, r) => { g.fillStyle = '#39393d'; g.fillRect(0, 0, S, S); g.fillStyle = '#2a2a2c'; g.beginPath(); g.arc(256, 256, 236, 0, 7); g.fill(); g.fillStyle = '#4a4a4e'; g.beginPath(); g.arc(256, 256, 220, 0, 7); g.fill(); g.strokeStyle = '#2a2a2c'; g.lineWidth = 10; for (let k = -4; k <= 4; k++) { g.beginPath(); g.moveTo(256 + k * 44, 60); g.lineTo(256 + k * 44, 452); g.stroke(); g.beginPath(); g.moveTo(60, 256 + k * 44); g.lineTo(452, 256 + k * 44); g.stroke(); } g.strokeStyle = '#1e1e20'; g.lineWidth = 14; g.beginPath(); g.arc(256, 256, 228, 0, 7); g.stroke(); grain(g, r, 6000, 0.08); });
    add('cone', (g, r) => { g.fillStyle = '#ff6a00'; g.fillRect(0, 0, S, S); g.fillStyle = '#fff'; g.fillRect(0, 160, S, 60); g.fillRect(0, 300, S, 60); });
    add('barrier', (g, r) => { for (let i = 0; i < 8; i++) { g.fillStyle = i % 2 ? '#ffffff' : '#ff6a00'; g.fillRect(i * 64, 0, 64, S); } });
    // Purpose-painted landmark panel: compensate for the wide physical sign so type keeps its proportions.
    add('vossSign', g => { g.fillStyle='#163b3e'; g.fillRect(0,0,S,S); g.fillStyle='#eec778'; g.fillRect(12,20,488,12); g.fillRect(12,480,488,12); g.save(); g.scale(1,6.67); g.font='900 58px Impact, Arial Black, sans-serif'; g.textAlign='center'; g.textBaseline='middle'; g.fillText('VOSS MOTORS',256,38.4,470); g.restore(); g._lit.push([0,0,S,S]); });
    return { color: layers, normal: normals, panes };
  }
  return { build, preload, names, S, NS, base, flatN, get layers() { return layers; }, get normals() { return normals; }, get shopKinds() { return shopKinds; } };
})();
