#!/usr/bin/env python3
"""Bake the downloaded ambientCG materials into js/texdata.js.

Each material becomes three data URIs: a colour map, a normal map (GL convention,
Y up) and a roughness map. The game paints the colour map as the base layer of a
texture and its detail on top, and feeds the normal and roughness to the shader.

Usage: bake-textures.py <cache-dir> <out.js> [spec.json]
Materials are downloaded by fetch-textures.py; everything is CC0 (SOURCES.md).
"""
import sys, os, io, json, base64
from PIL import Image, ImageEnhance
import numpy as np

def data_uri(im, fmt='JPEG', **kw):
    b = io.BytesIO(); im.save(b, fmt, **kw)
    return 'data:image/%s;base64,%s' % (fmt.lower(), base64.b64encode(b.getvalue()).decode())

def normal_gain(im, target, cap):
    """Tiling a normal map down to a few hundred pixels averages opposing slopes away, so the relief nearly
    vanishes. Measure what is left and push X and Y back out until the map deviates by `target` again."""
    a = np.asarray(im.convert('RGB')).astype(np.float32)
    dev = float(np.mean(np.abs(a[:, :, 0] - 128) + np.abs(a[:, :, 1] - 128)) / 2)
    if dev < 0.05: return im, 1.0
    gain = min(cap, max(1.0, target / dev))
    if gain <= 1.01: return im, 1.0
    a[:, :, 0] = np.clip((a[:, :, 0] - 128) * gain + 128, 0, 255)
    a[:, :, 1] = np.clip((a[:, :, 1] - 128) * gain + 128, 0, 255)
    # keep it a unit normal: z from the amplified x and y
    x = (a[:, :, 0] / 127.5 - 1.0); y = (a[:, :, 1] / 127.5 - 1.0)
    a[:, :, 2] = np.clip(np.sqrt(np.clip(1.0 - x * x - y * y, 0.0, 1.0)) * 127.5 + 127.5, 0, 255)
    return Image.fromarray(a.astype(np.uint8)), gain

def tiled(im, n, size):
    """Resize to `size`, repeating the material n times across it."""
    if n <= 1: return im.resize((size, size), Image.LANCZOS)
    cell = max(1, size // n); small = im.resize((cell, cell), Image.LANCZOS)
    out = Image.new(im.mode, (size, size))
    for y in range(0, size, cell):
        for x in range(0, size, cell): out.paste(small, (x, y))
    return out

def main(cache, out_path, spec_path):
    spec = json.load(open(spec_path)); Q = spec['quality']
    mats = {}
    for layer, e in spec['layers'].items():
        m = e.get('material')
        if not m or m in mats: continue
        d = os.path.join(cache, m)
        if not os.path.exists(os.path.join(d, 'Color.jpg')):
            print('  missing', m, '- run fetch-textures.py first'); continue
        col = Image.open(os.path.join(d, 'Color.jpg')).convert('RGB')
        col = tiled(col, e.get('tile', 1), Q['color'])
        if e.get('sat', 1) != 1: col = ImageEnhance.Color(col).enhance(e['sat'])
        if e.get('bright', 1) != 1: col = ImageEnhance.Brightness(col).enhance(e['bright'])
        entry = {'c': data_uri(col, quality=Q['colorQ'])}
        np_ = os.path.join(d, 'Normal.jpg'); gain = 1.0
        if os.path.exists(np_):
            nm = tiled(Image.open(np_).convert('RGB'), e.get('tile', 1), Q['normal'])
            nm, gain = normal_gain(nm, e.get('nrmTarget', Q.get('nrmTarget', 14)), e.get('nrmCap', Q.get('nrmCap', 4.0)))
            entry['n'] = data_uri(nm, quality=Q['normalQ'], subsampling=0)
        rp = os.path.join(d, 'Roughness.jpg')
        if os.path.exists(rp):
            rm = tiled(Image.open(rp).convert('L'), e.get('tile', 1), Q['rough'])
            entry['r'] = data_uri(rm, quality=Q['roughQ'])
        mats[m] = entry
        print('  %-18s %5dK colour %4dK normal %3dK rough  gain x%.1f' % (m, len(entry['c']) // 1024, len(entry.get('n', '')) // 1024, len(entry.get('r', '')) // 1024, gain))
    by_layer = {k: [e['material'], e.get('tint', 0.3)] for k, e in spec['layers'].items() if e.get('material') in mats}
    js = ("// Generated by tools/assets/bake-textures.py from ambientCG materials (CC0; see tools/assets/SOURCES.md). Do not edit.\n"
          "'use strict';\nconst TEXDATA = " + json.dumps({'layers': by_layer, 'mats': mats}, separators=(',', ':')) + ";\n")
    open(out_path, 'w').write(js)
    print('wrote %s  %d materials  %d KB' % (out_path, len(mats), len(js) // 1024))

if __name__ == '__main__':
    spec = sys.argv[3] if len(sys.argv) > 3 else os.path.join(os.path.dirname(__file__), 'textures.json')
    main(sys.argv[1], sys.argv[2], spec)
