"""Turning archive elites into games worth handing to a person.

MAP-Elites optimises for filling cells, and a cell is filled by whatever scored
best in it, which is not the same as a game anyone would play.  Two things are
usually wrong with an elite straight out of the archive:

* **Its levels are inherited.** The mutation operators change rules freely and
  levels only a tile at a time, so a game that gained a growth mechanic is
  still being played on a Sokoban's level, where the new mechanic may never
  fire.
* **Nothing has asked it the expensive questions.** Tier-1 fitness knows the
  game is solvable and covers its rules. It does not know whether random play
  beats it or whether any move on the solution path matters.

So the finishing pass regenerates each candidate's levels against its *own*
rules with the solver in the loop (``prof.levelgen``), keeps the result only if
it measures better, scores the survivors on the depth metrics
(``prof.depth``), and writes the ones that pass a quality bar to
``data/archive/`` with a gallery.

    .venv/bin/python -m prof.polish --runs data/evolve/novel data/evolve/control \\
        --top 40 --workers 4

A game reaches the output only if every probed level is solvable, no level is
won by random play, and its rules all fire on some solution.
"""
from __future__ import annotations

import argparse
import json
import random
import shutil
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "archive"


@dataclass
class Polished:
    key: str
    run: str
    name: str
    ops: list[str] = field(default_factory=list)
    fitness: float = 0.0
    novelty: float = 0.0
    regenerated: bool = False
    coverage: float = -1.0            # fraction of rules that fire on a solution
    before: dict[str, Any] | None = None
    after: dict[str, Any] | None = None
    note: str = ""
    seconds: float = 0.0

    def score(self) -> float:
        """Rank for the final listing: playable first, then deep, then novel.

        Terms that could not be measured are dropped rather than scored zero.
        The fatal-move structure is only trustworthy where the survival probe
        re-solved the known solution path (``reliable_levels``), and a game
        whose branching defeated the probe should not be ranked below one that
        was merely measured.
        """
        d = self.after or {}
        if not d or d.get("solved", 0) == 0:
            return -1.0
        parts = [
            1.0 - min(1.0, d.get("random_win_frac", 0.0) * 4),   # not a walkover
            0.5 + 0.5 * min(1.0, d.get("insight", 0.0)),         # greedy struggles
            min(1.0, self.novelty / 1.4),                        # unlike the corpus
        ]
        if d.get("reliable_levels", 0):
            parts.append(min(1.0, d.get("fatal_gini", 0.0)))     # danger concentrated
            if d.get("fatal_frac", 0.0) > 0.8:
                parts.append(0.0)                                # a guessing game
        return sum(parts) / len(parts)


def provenance(text: str, key: str, run: str, ops: list[str],
               regenerated: bool) -> str:
    """Retitle a derived game and record where it came from.

    These are derived works: every one of them started as a human-authored game
    from the corpus, and shipping them under the original title and author
    would misattribute both the credit and the blame. The original author stays
    named, the machine's part is stated, and the mutation chain is written into
    the file so any game in the archive can be traced back.
    """
    from prof.grammar import Game

    try:
        g = Game.parse(text)
    except Exception:  # noqa: BLE001
        return text
    parent_title = g.title()
    author = "unknown"
    for line in g.prelude:
        if line.lower().startswith("author "):
            author = line[7:].strip()
            break
    note = [
        "(",
        f"  Generated by ScriptProf on {time.strftime('%Y-%m-%d')}.",
        f"  Descended from \"{parent_title}\" by {author}, from the PuzzleScript corpus.",
        f"  Archive cell {key} of run {run}.",
        f"  Mutations applied: {', '.join(ops) if ops else 'none (seed)'}.",
    ]
    if regenerated:
        note.append("  Levels regenerated by search against this game's own rules.")
    note.append(")")
    g.prelude = [l for l in g.prelude
                 if not l.lower().startswith(("title ", "author "))]
    g.prelude = note + [f"title {parent_title} ({key})",
                        f"author ScriptProf, after {author}"] + g.prelude
    # repair here as well as in the level installer, so a game that kept its
    # original levels still gets vacuous win conditions and stranded objects
    # cleaned before it ships
    g.repair()
    return g.emit()


def _quality_ok(rec: "Polished", min_coverage: float) -> bool:
    """The bar a game has to clear to be shipped.

    Rule coverage is the one that does the most work. Across the novelty run's
    122 playable elites the mean was 0.58 -- nearly half the rules in a typical
    archive game never fire on any solution path. That is precisely the failure
    GAVEL reports (unused game components) and precisely what PuzzleScript
    makes visible, and MAP-Elites will not fix it on its own: a bloated game
    can be the best thing in a high-rule-count cell and still be mostly dead
    code. Filtering here keeps the search free to explore and the output
    honest.
    """
    d = rec.after
    if not d or d.get("error"):
        return False
    if d.get("analysed", 0) == 0 or d.get("solved", 0) < d.get("analysed", 0):
        return False
    if d.get("random_win_frac", 1.0) > 0.02:
        return False
    if rec.coverage >= 0 and rec.coverage < min_coverage:
        return False
    if d.get("reliable_levels", 0) and d.get("fatal_frac", 0.0) > 0.8:
        return False                      # every move loses: a guessing game
    return True


def polish_one(job) -> dict[str, Any]:
    """Regenerate one elite's levels, measure before and after, keep the better."""
    key, run_name, text, meta, cfg = job
    t0 = time.time()
    from prof.depth import analyse
    from prof.fitness import evaluate
    from prof.levelgen import LevelGen

    p = Polished(key=key, run=run_name, name=meta.get("name", key),
                 ops=meta.get("ops", []), fitness=meta.get("fitness", 0.0),
                 novelty=meta.get("novelty", 0.0))
    # The structural half needs a PuzzleJAX trace, whose cost grows with the
    # game; spend it only on games small enough for it to return in seconds.
    structure = cfg["structure"] and len(text.splitlines()) <= cfg["structure_lines"]
    try:
        before = analyse(text, max_levels=cfg["levels"], structure=structure,
                         timeout_ms=cfg["timeout_ms"], max_iters=cfg["max_iters"])
        p.before = before.to_dict()
    except Exception as e:  # noqa: BLE001
        p.note = f"before: {type(e).__name__}"
        p.seconds = time.time() - t0
        return {"rec": asdict(p), "text": text}

    best_text, best = text, p.before
    try:
        gen = LevelGen(text, height=cfg["height"], width=cfg["width"])
        cands = gen.run(pop=cfg["pop"], generations=cfg["gens"],
                        target_len=cfg["target_len"], min_len=cfg["min_len"],
                        seed=cfg["seed"], verbose=False, backend="cpp",
                        solve_iters=cfg["gen_iters"],
                        solve_timeout_ms=cfg["gen_timeout_ms"])
        candidate = gen.install(cands, n=cfg["keep_levels"])
        ev = evaluate(candidate, max_levels=cfg["levels"], timeout_ms=4000)
        if ev.tier >= 3:
            after = analyse(candidate, max_levels=cfg["levels"], structure=structure,
                            timeout_ms=cfg["timeout_ms"], max_iters=cfg["max_iters"])
            # Only adopt regenerated levels if they are actually better play
            # AND actually different.  LevelGen.install returns the game
            # unchanged when nothing solvable was found, and comparing that
            # against itself always passes, so every total generation failure
            # was being recorded as a success.
            changed = candidate.strip() != text.strip()
            if (changed and after.solved >= before.solved
                    and after.agg("random_win_frac", False)
                    <= before.agg("random_win_frac", False)):
                best_text, best = candidate, after.to_dict()
                p.regenerated = True
            elif not changed:
                p.note = (p.note + " | " if p.note else "") + "regen found nothing"
        else:
            p.note = f"regen not playable (tier {ev.tier})"
    except Exception as e:  # noqa: BLE001
        p.note = f"regen: {type(e).__name__}: {e}"[:100]
    p.after = best
    try:
        final = evaluate(best_text, max_levels=cfg["levels"], timeout_ms=4000)
        if final.coverage and final.coverage.get("n_rules"):
            p.coverage = final.coverage["n_fired"] / final.coverage["n_rules"]
    except Exception:  # noqa: BLE001
        pass
    p.seconds = time.time() - t0
    titled = provenance(best_text, key, run_name, p.ops, p.regenerated)
    # provenance rewrites the prelude, so make sure it still compiles
    try:
        from prof import engine as E

        E.compile_text(titled, timeout=20)
        best_text = titled
    except Exception:  # noqa: BLE001
        p.note = (p.note + " | " if p.note else "") + "provenance skipped"
    return {"rec": asdict(p), "text": best_text}


def collect(runs: list[Path], top: int, max_lines: int = 400,
            max_rules: int = 120) -> list[tuple]:
    """The most promising elites across the given runs.

    Size is a hard filter, not a preference.  Mutation can pile rules onto a
    game indefinitely, and the archive has cells that reward exactly that; a
    two-thousand-line elite costs minutes to trace in PuzzleJAX and is not a
    game anyone will read.  Anything past the cap is left in the archive.
    """
    jobs = []
    skipped = 0
    for run in runs:
        idx = run / "archive.json"
        if not idx.exists():
            print(f"  skip {run}: no archive.json")
            continue
        blob = json.loads(idx.read_text())
        elites = blob["elites"]
        ranked = sorted(
            ((k, e) for k, e in elites.items() if e["tier"] >= 3),
            key=lambda kv: -(kv[1]["fitness"] + 0.3 * kv[1].get("novelty", 0)))
        taken = 0
        for k, e in ranked:
            if taken >= top:
                break
            src = run / "games" / f"{k}.txt"
            if not src.exists():
                continue
            text = src.read_text(encoding="utf-8", errors="replace")
            if (len(text.splitlines()) > max_lines
                    or e.get("features", {}).get("n_rule_sources", 0) > max_rules):
                skipped += 1
                continue
            jobs.append((k, run.name, text, e))
            taken += 1
    if skipped:
        print(f"  skipped {skipped} elites over the size cap "
              f"({max_lines} lines / {max_rules} rules)")
    return jobs


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", nargs="+", default=["data/evolve/novel", "data/evolve/control"])
    ap.add_argument("--out", default="data/archive")
    ap.add_argument("--top", type=int, default=40)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--levels", type=int, default=3)
    ap.add_argument("--pop", type=int, default=64)
    ap.add_argument("--gens", type=int, default=5)
    ap.add_argument("--height", type=int, default=8)
    ap.add_argument("--width", type=int, default=8)
    ap.add_argument("--target-len", type=int, default=16)
    ap.add_argument("--min-len", type=int, default=6)
    ap.add_argument("--keep-levels", type=int, default=4)
    ap.add_argument("--min-coverage", type=float, default=0.6,
                    help="reject games where fewer than this fraction of rules fire")
    ap.add_argument("--no-structure", action="store_true")
    ap.add_argument("--structure-lines", type=int, default=220,
                    help="skip the PuzzleJAX half for games longer than this")
    ap.add_argument("--max-lines", type=int, default=400)
    ap.add_argument("--max-rules", type=int, default=120)
    ap.add_argument("--timeout-ms", type=int, default=3000)
    ap.add_argument("--gen-iters", type=int, default=25_000)
    ap.add_argument("--gen-timeout-ms", type=int, default=700)
    ap.add_argument("--max-iters", type=int, default=80_000)
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()

    runs = [Path(r) if Path(r).is_absolute() else ROOT / r for r in a.runs]
    out = Path(a.out) if Path(a.out).is_absolute() else ROOT / a.out
    jobs_raw = collect(runs, a.top, a.max_lines, a.max_rules)
    print(f"{len(jobs_raw)} elites from {len(runs)} runs", flush=True)
    if not jobs_raw:
        return
    cfg = {"levels": a.levels, "pop": a.pop, "gens": a.gens, "height": a.height,
           "width": a.width, "target_len": a.target_len, "min_len": a.min_len,
           "keep_levels": a.keep_levels, "seed": a.seed,
           "structure": not a.no_structure, "structure_lines": a.structure_lines,
           "gen_iters": a.gen_iters, "gen_timeout_ms": a.gen_timeout_ms,
           "timeout_ms": a.timeout_ms, "max_iters": a.max_iters}
    jobs = [(k, r, t, m, cfg) for k, r, t, m in jobs_raw]

    out.mkdir(parents=True, exist_ok=True)
    games_dir = out / "games"
    games_dir.mkdir(exist_ok=True)
    recs: list[Polished] = []
    texts: dict[str, str] = {}
    t0 = time.time()
    from prof.pool import resilient_map

    n_crash = 0
    for i, res, reason in resilient_map(polish_one, jobs, a.workers):
        if res is None:
            n_crash += 1
            print(f"  [{i + 1}/{len(jobs)}] crashed: {reason}", flush=True)
            continue
        rec = Polished(**res["rec"])
        recs.append(rec)
        texts[f"{rec.run}_{rec.key}"] = res["text"]
        d = rec.after or {}
        print(f"  [{i + 1}/{len(jobs)} {time.time() - t0:.0f}s] {rec.run}/{rec.key} "
              f"regen={rec.regenerated} solved={d.get('solved', 0)}/{d.get('analysed', 0)} "
              f"cov={rec.coverage:.2f} rand={d.get('random_win_frac', 0):.2f} "
              f"score={rec.score():.2f} {rec.note[:36]}", flush=True)

    keepers = [r for r in recs if _quality_ok(r, a.min_coverage)]
    keepers.sort(key=lambda r: -r.score())
    for r in keepers:
        name = f"{r.run}_{r.key}"
        (games_dir / f"{name}.txt").write_text(texts[name], encoding="utf-8")
    # a text file is not something you can hand anyone; a self-contained
    # player is
    try:
        from prof.standalone import export

        play_dir = out / "play"
        for r in keepers:
            export(games_dir / f"{r.run}_{r.key}.txt", play_dir)
        print(f"playable HTML -> {play_dir}")
    except Exception as e:  # noqa: BLE001
        print(f"standalone export skipped: {type(e).__name__}: {e}")
    (out / "index.json").write_text(json.dumps(
        {"generated": time.strftime("%Y-%m-%d %H:%M"),
         "runs": [str(r) for r in runs],
         "considered": len(recs), "kept": len(keepers),
         "games": [asdict(r) | {"final_score": r.score()} for r in keepers]}, indent=1))
    n_regen = sum(1 for r in keepers if r.regenerated)
    print(f"\n{len(keepers)}/{len(recs)} passed the bar (every level solvable, "
          f"random play never wins, >={100 * a.min_coverage:.0f}% of rules fire); "
          f"{n_regen} kept regenerated levels")
    print(f"written to {out}")
    for r in keepers[:12]:
        d = r.after or {}
        print(f"  {r.score():.2f}  {r.run}/{r.key:14s} nov={r.novelty:.2f} "
              f"cov={r.coverage:.2f} insight={d.get('insight', 0):.2f} "
              f"{'+'.join(r.ops)[:46]}")


if __name__ == "__main__":
    main()
